# This is an autogenerated file. Do not change it manually.
# Any changes you make here WILL be overwritten!

TARGETS = build-test-images check-coverage list-pragmas makefile test test-html
.PHONY: $(TARGETS)

PYTHON = python

$(TARGETS):
	$(PYTHON) make.py $@
