# This is an autogenerated file. Do not change it manually.
# Any changes you make here WILL be overwritten!

TARGETS = check-coverage list-pragmas makefile test test-html
.PHONY: $(TARGETS)

PYTHON = uv run python

$(TARGETS):
	$(PYTHON) make.py $@
