# SPDX-FileCopyrightText: 2025-2026 Ohad Livne <libohad-dev@proton.me>
#
# SPDX-License-Identifier: CC0-1.0

[project]
name = "temper-edit"
version = "0.1.0"
description = "Perform atomic edit of files through a temporary copy"
authors = [
  {name = "Ohad Livne", email = "libohad-dev@proton.me"}
]
license = "GPL-3.0-or-later"
license-files = ["LICENSES"]
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
  "Programming Language :: Python :: 3",
]
dependencies = [
  # keep-sorted start
  "pydantic >=2.12, <3",
  # keep-sorted end
]

[project.scripts]
temper-edit = "temper_edit.cli:run"

[dependency-groups]
dev = [
  # keep-sorted start
  "case-converter >=1.2.0, <2",
  "coverage >=7.13.1, <8",
  "debugpy >=1.8.14, <2",
  "pytest >=8.4.0, <9",
  "pytest-cov >=6.2.1, <7",
  "pytest-xdist >=3.8.0, <4.0.0",
  "tach >=0.25, <1",
  "testcontainers >=4.13, <5",
  # keep-sorted end
]

[tool.coverage.run]
parallel = true
relative_files = true
source = ["src/temper_edit", "tests"]

[tool.coverage.paths]
source = [
  "src/temper_edit",
  "/app/temper_edit",
]

[tool.coverage.report]
show_missing = true

[tool.coverage.html]
directory = "htmlcov"

[tool.mypy]
mypy_path = "./src:./tests"

plugins = [
  "pydantic.mypy"
]

strict = true
warn_unreachable = true

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
warn_untyped_fields = true

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
  # keep-sorted start
  "B",  # flake8-bugbear
  "I",  # isort
  "PTH",  # flake8-use-pathlib
  "RET",  # flake8-return
  "SIM",  # flake8-simplify
  "UP",  # pyupgrade
  # keep-sorted end
  # keep-sorted start
  "F401",  # remove unused imports
  # keep-sorted end
]
ignore = [
  # keep-sorted start
  "RET505",  # Unnecessary branch after return
  "RET506",  # Unnecessary branch after raise
  "RET507",  # Unnecessary branch after continue
  "RET508",  # Unnecessary branch after break
  # keep-sorted end
]
