# SPDX-FileCopyrightText: 2025-2026 Ohad Livne <libohad-dev@proton.me>
#
# SPDX-License-Identifier: CC0-1.0

[project]
name = "temper-edit"
version = "1.2.1"
description = "Perform atomic edit of files through a temporary copy"
authors = [
  {name = "Ohad Livne", email = "libohad-dev@proton.me"}
]
license = "GPL-3.0-or-later"
license-files = ["LICENSES"]
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
  # keep-sorted start
  "Development Status :: 5 - Production/Stable",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "Intended Audience :: System Administrators",
  "Operating System :: POSIX",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: System :: Systems Administration",
  "Topic :: Text Editors",
  "Topic :: Utilities",
  "Typing :: Typed",
  # keep-sorted end
]
dependencies = []

[project.optional-dependencies]
s3 = ["boto3>=1.26"]

[project.scripts]
temper-edit = "temper_edit.cli:run"

[dependency-groups]
dev = [
  # keep-sorted start
  "boto3>=1.26",
  "case-converter >=1.2.0, <2",
  "debugpy >=1.8.14, <2",
  "pytest >=8.4.0, <9",
  "pytest-cov >=6.2.1, <7",
  "pytest-xdist >=3.8.0, <4.0.0",
  "tach >=0.25, <1",
  "testcontainers[minio] >=4.13, <5",
  # keep-sorted end
]

[tool.coverage.run]
omit = [
  # keep-sorted start
  "tests/commit_security_script.py",
  "tests/conftest.py",
  "tests/elevated_commit_security_script.py",
  # keep-sorted end
]
branch = true
parallel = true
relative_files = true
source = ["src/temper_edit", "tests"]

[tool.coverage.paths]
source = [
  "src/temper_edit",
  "/app/temper_edit",
]

[tool.coverage.report]
fail_under = 100
show_missing = true

[tool.coverage.html]
directory = "htmlcov"

[tool.mypy]
mypy_path = "./src:./tests"

strict = true
warn_unreachable = true

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
  # keep-sorted start
  "B",  # flake8-bugbear
  "I",  # isort
  "PTH",  # flake8-use-pathlib
  "RET",  # flake8-return
  "SIM",  # flake8-simplify
  "UP",  # pyupgrade
  # keep-sorted end
  # keep-sorted start
  "F401",  # remove unused imports
  # keep-sorted end
]
ignore = [
  # keep-sorted start
  "RET505",  # Unnecessary branch after return
  "RET506",  # Unnecessary branch after raise
  "RET507",  # Unnecessary branch after continue
  "RET508",  # Unnecessary branch after break
  # keep-sorted end
]
