# SPDX-FileCopyrightText: 2025 Ohad Livne <libohad-dev@proton.me>
#
# SPDX-License-Identifier: CC0-1.0

exclude = ["**/__pycache__", "build/", "dist/", ".venv/", "tests/"]
source_roots = ["src"]
exact = true
# keep-sorted start
forbid_circular_dependencies = true
ignore_type_checking_imports = false
root_module = "forbid"
# keep-sorted end

[rules]
# keep-sorted start
require_ignore_directive_reasons = "error"
unused_external_dependencies = "error"
unused_ignore_directives = "error"
# keep-sorted end

[[modules]]
path = "temper_edit.base_model"
depends_on = []

[[modules]]
path = "temper_edit.exceptions"
depends_on = []

[[modules]]
path = "temper_edit.config"
depends_on = [
    # keep-sorted start
    "temper_edit.base_model",
    # keep-sorted end
]

[[modules]]
path = "temper_edit.editor"
depends_on = [
    # keep-sorted start
    "temper_edit.config",
    "temper_edit.exceptions",
    # keep-sorted end
]

[[modules]]
path = "temper_edit.atomic_edit"
depends_on = []

[[modules]]
path = "temper_edit.cli"
depends_on = [
    # keep-sorted start
    "temper_edit.atomic_edit",
    "temper_edit.config",
    "temper_edit.editor",
    # keep-sorted end
]
