# SPDX-FileCopyrightText: 2025-2026 Ohad Livne <libohad-dev@proton.me>
#
# SPDX-License-Identifier: GPL-3.0-or-later

ARG IMAGE_TAG
FROM docker.io/astral/uv:${IMAGE_TAG}

RUN apk add coreutils && \
    adduser -D -u 1000 user && \
    uv pip install --system coverage[toml]
