# SPDX-FileCopyrightText: 2025-2026 Ohad Livne <libohad-dev@proton.me>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Locally-built base image with all external dependencies
ARG IMAGE_TAG
FROM localhost/temper-edit-test-base:${IMAGE_TAG}

WORKDIR /app
COPY pyproject.toml .
COPY src/ .
RUN uv venv --system-site-packages && \
    uv pip install --no-deps --editable . && \
    chmod --recursive a+rX temper_edit && \
    rm /tmp/uv-*.lock
WORKDIR /root

ENTRYPOINT ["/bin/sleep"]
CMD ["infinity"]
